spring:
  cloud:
   config:
    name: profile
  jpa:
    hibernate:
      ddl-auto: update
      jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      
      
      